const Discord = require("discord.js"); global.Discord = Discord;
const bot = new Discord.Client(); global.bot = bot;
const mysql = require("mysql"); global.mysql = mysql;
const snekfetch = require("snekfetch"); global.snekfetch = snekfetch;
const ntc = require("ntc"); global.ntc = ntc;
const Canvas = require("canvas"); global.Canvas = Canvas;
const moment = require("moment"); global.moment = moment;
const TikTokScraper = require("tiktok-scraper"); global.TikTokScraper = TikTokScraper;
const InstagramScrapper = require("instagram-scraping"); global.InstagramScrapper = InstagramScrapper;
const samplookup = require("samp-query"); global.samplookup = samplookup;
const YTBScrape = require("scrape-yt"); global.YTBScrape = YTBScrape;
const YouTubeScrapper = require("yt-channel-info"); global.YouTubeScrapper = YouTubeScrapper;
const ipinfo = require("ipinfo"); global.ipinfo = ipinfo;
const system_information = require("systeminformation"); global.system_information = system_information;
const fs = require("fs"); global.fs = fs;
//const Meme = require("memer-api"), memer = new Meme(); global.Meme = Meme;
const ytdl = require("discord-ytdl-core"); global.ytdl = ytdl;
const yts = require("yt-search"); global.yts = yts;
const { NodeSSH } = require("node-ssh"); global.NodeSSH = NodeSSH;
const speedTest = require('speedtest-net'); global.speedTest = speedTest;
const request = require("request"); global.request = request;
const spdl = require("spdl-core"); global.spdl = spdl;
